config/routes.rb
Rails.application.routes.draw do
  root 'main_admin#index'
  resources :requests, only: %i[index show update destroy]
  devise_for :admins, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret'
  }, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  resources :users, only: %i[index show update]
  resources :shops, only: %i[index show update] do
    collection do
      resources :products do
        collection do
          get 'sub/:id', controller: 'products', action: 'sub'
        end
      end
    end
  end
  resources :purchase_orders, only: %i[index show new create destroy] do
    collection do
      post 'product'
      get 'products/:id', controller: 'purchase_orders', action: 'delete_product'
    end
  end
  resources :delivery_orders, only: %i[index show edit update]
  resources :categories
  resources :sub_categories
  resources :admins, only: %i[index show new create update]
  resources :main_admin, only: :index
  resources :revenue, only: :index do
    member do
      get :revenue
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true, class: "form-horizontal col-md-6 col-sm-offset-3") do |form| %>
<% if admin.errors.any? %>
<% admin.errors.full_messages.each do |message| %>
<script>
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= message %>');
</script>
<% end %>
<% end %>

<div class="form-group">
  <%= form.label :username, class: "control-label col-sm-2" %>
  <div class="col-sm-10">
    <%= form.text_field :username, id: :admin_username, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :email, class: "control-label col-sm-2" %>
  <div class="col-sm-10">
    <%= form.text_field :email, id: :admin_email, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :name, class: "control-label col-sm-2" %>
  <div class="col-sm-10">
    <%= form.text_field :name, id: :admin_name, class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <%= form.label :gender, class: "control-label col-sm-2" %>
  <div class="col-sm-10">
    <%= form.radio_button :gender, "male", checked: true %>Male
    <%= form.radio_button :gender, "female" %>Female
    <%= form.radio_button :gender, "ohter" %>Other
  </div>
</div>

<div class="actions">
  <%= form.submit class: "btn btn-primary pull-right" %>
  <%= link_to 'Back', admins_path, class: "btn btn-default pull-right" %>
</div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<% unless notice.nil? %>
<% unless notice['message'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.success('<%= notice['message'] %>').dismissOthers();
</script>
<% end %>
<% unless notice['errors'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= notice['errors'] %>').dismissOthers();
</script>
<% end %>
<% end %>
<div class="clearfix"></div>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Admins</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a href="#"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <% if current_admin.manager? %>
      <% if can? :create, Admin %>
      <%= link_to 'New Admin', new_admin_path, class: 'btn btn-primary' %>
      <% end %>
      <% end %>
      <% if (@admins.count > 0) %>
      <table id="datatable-buttons-admin" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Name</th>
            <th>Role</th>
            <th>Manager</th>
            <th>Available</th>
            <th>Show</th>
            <th>Edit</th>
          </tr>
        </thead>

        <tbody>
          <% @admins.each do |admin| %>
          <tr>
            <td><%= admin.username %></td>
            <td><%= admin.email %></td>
            <td><%= admin.name %></td>
            <td><%= admin.role %></td>
            <td><%= admin.manager.name unless admin.manager.nil? %></td>
            <td><%= admin.available %></td>
            <td><%= link_to admin_path(admin) do %>
              <button class="btn btn-primary btn-xs" ><span class="fa fa-search"></span></button>
              <% end %>
            </td>
            <td><%= link_to admin_path(admin), method: :put, data: { confirm: 'Are you sure?' } do %>
              <button class="btn btn-primary btn-xs"><span class="<%= admin.available == true ? 'fa fa-lock' : 'fa fa-unlock' %>"></span></button>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <h2>You don't manage anyone!</h2>
      <% end %>
    </div>
  </div>
</div>
<br>
<div class="clearfix"></div>
<%= javascript_include_tag 'datatables/jquery.dataTables.min' %>
<%= javascript_include_tag 'datatables/dataTables.bootstrap' %>
<%= javascript_include_tag 'datatables/dataTables.buttons.min' %>
<%= javascript_include_tag 'datatables/jszip.min.js' %>
<%= javascript_include_tag 'datatables/pdfmake.min' %>
<%= javascript_include_tag 'datatables/vfs_fonts' %>
<%= javascript_include_tag 'datatables/buttons.html5.min' %>
<%= javascript_include_tag 'datatables/buttons.print.min' %>
<%= javascript_include_tag 'datatables/dataTables.responsive.min' %>
<%= javascript_include_tag 'datatables/responsive.bootstrap.min' %>
<%= javascript_include_tag params[:controller] %>

app/views/admins/new.html.erb
<div class="clearfix"></div>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Admins</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a href="#"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <%= render 'form', admin: @admin %>
    </div>
  </div>
</div>
<br>

app/views/admins/show.html.erb
<% unless notice.nil? %>
<% unless notice['message'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.success('<%= notice['message'] %>').dismissOthers();
</script>
<% end %>
<% unless notice['errors'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= notice['errors'] %>').dismissOthers();
</script>
<% end %>
<% end %>
<div class="">
  <div class="clearfix"></div>

  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Detail of Order</strong></h2>
          <ul class="nav navbar-right panel_toolbox">
            <li><a href="#"><i class="fa fa-chevron-up"></i></a>
            </li>
            <li><a href="#"><i class="fa fa-close"></i></a>
            </li>
          </ul>
          <div class="clearfix"></div>
        </div>
        <div class="x_content">
          <div class="col-md-4 col-sm-4 col-xs-12">
            <div class="product-image" style="padding-top: 30px;">
              <% if @admin.role === 'admin' %>
              <img src="http://www.lets-develop.com/wp-content/themes/olivias_theme/images/custom-avatar-admin.jpg" class="img-thumbnail" alt="admin" />
              <% elsif @admin.role === 'manager' %>
              <img src="https://bootstrapmaster.com/wp-content/themes/bootstrap/img/avatars/noavatar.png" class="img-thumbnail" alt="manager" />
              <% else %>
              <img src="http://bodyworkshealthclinic.com/images/avatar.png" class="img-thumbnail" alt="partner" />
              <% end %>
            </div>
          </div>

          <div class="col-md-8 col-sm-8 col-xs-12" style="border:0px solid #e5e5e5;">
            <h2 class="prod_title"><%= @admin.name %></h2>
            <div class="table-full-width">
              <table class="table table-bordered">
                <tbody>
                  <tr>
                    <td width="30%">Username</td>
                    <td><strong><%= @admin.username %></strong></td>
                  </tr>
                  <tr>
                    <td width="30%">Email</td>
                    <td><strong><%= @admin.email %></strong></td>
                  </tr>
                  <tr>
                    <td width="30%">Full name</td>
                    <td><strong><%= @admin.name %></strong></td>
                  </tr>
                  <tr>
                    <td width="30%">Role</td>
                    <td><strong><%= @admin.role %></strong></td>
                  </tr>
                  <% if @admin.role === 'partner' %>
                  <tr>
                    <td width="30%">Manager</td>
                    <td><strong><%= Admin.find(@admin.manager_id).name %></strong></td>
                  </tr>
                  <% end %>
                  <tr>
                    <td width="30%">Gender</td>
                    <td><strong><%= @admin.gender %></strong></td>
                  </tr>
                  <% if @admin.role != 'admin' %>
                  <tr>
                    <td width="30%">Shop</td>
                    <td><strong><%= Shop.find(@admin.shop_id).name %></strong></td>
                  </tr>
                  <% end %>
                  <% if @admin.role != 'admin' %>
                  <% if @admin.role == 'manager' %>
                  <tr>
                    <td width="30%">Partner</td>
                    <td><strong>
                      <%
                      @partners = Admin.where(manager_id: @admin.id)
                      @partners.each do |partner|
                      %>
                      <%= link_to partner.name, admin_path(partner) %>,
                      <% end %>
                    </strong></td>
                  </tr>
                  <% else %>
                  <tr>
                    <td width="30%">Manager</td>
                    <td><strong>
                      <%= link_to @admin.manager.name, admin_path(@admin.manager) %>,
                    </strong></td>
                  </tr>
                  <% end %>
                  <% end %>
                  <tr>
                    <td width="30%">Status</td>
                    <% if @admin.available %>
                    <td><strong>Available</strong></td>
                    <% else %>
                    <td><strong>Non-available</strong></td>
                    <% end %>
                  </tr>
                </tbody>
              </table>
              <% if @admin.available %>
              <%= link_to admin_path(@admin), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary pull-right' do%>
              <i class="fa fa-lock"></i>  Lock
              <% end %>
              <% else %>
              <%= link_to admin_path(@admin), method: :put, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary pull-right' do%>
              <i class="fa fa-unlock"></i>  Unlock
              <% end %>
              <% end %>
              <%= link_to 'Back', admins_path, class: "btn btn-default pull-right" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>