config/routes.rb
Rails.application.routes.draw do
  root 'main_admin#index'
  resources :requests, only: %i[index show update destroy]
  devise_for :admins, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret'
  }, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  resources :users, only: %i[index show update]
  resources :shops, only: %i[index show update] do
    collection do
      resources :products do
        collection do
          get 'sub/:id', controller: 'products', action: 'sub'
        end
      end
    end
  end
  resources :purchase_orders, only: %i[index show new create destroy] do
    collection do
      post 'product'
      get 'products/:id', controller: 'purchase_orders', action: 'delete_product'
    end
  end
  resources :delivery_orders, only: %i[index show edit update]
  resources :categories
  resources :sub_categories
  resources :admins, only: %i[index show new create update]
  resources :main_admin, only: :index
  resources :revenue, only: :index do
    member do
      get :revenue
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sub_category.rb
# == Schema Information
#
# Table name: sub_categories
#
#  id          :integer          not null, primary key
#  name        :string
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  slug        :string
#

class SubCategory < ApplicationRecord
  # =============Association=================
  belongs_to :category
  has_many :products, as: :categorical

  # ==============Friendly_url===============
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  load_and_authorize_resource find_by: :slug

  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    @sub_categories = SubCategory.where(category_id: params[:category_id])
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @category = Category.new
    @sub_category = SubCategory.new
    @categories = Category.all
  end

  # GET /sub_categories/1/edit
  def edit
    @categories = Category.all
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: { message: 'Sub category was successfully created.' } }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to @sub_category, notice: { message: 'Sub category was successfully updated.' } }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: { message: 'Sub category was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    if current_admin.nil?
      flash[:error] = "Access denied: #{exception}"
      redirect_to new_admin_session_path
    else
      render file: 'public/403.html', layout: false
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_sub_category
    @sub_category = SubCategory.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def sub_category_params
    params.require(:sub_category).permit(:name, :category_id)
  end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<div class="x_content">
  <br />
  <%= form_with(model: sub_category, local: true, id: "demo-form2", class: "form-horizontal form-label-left") do |form| %>
  <% if sub_category.errors.any? %>
  <% sub_category.errors.full_messages.each do |message| %>
  <script>
    alertify.set('notifier','position', 'top-right');
    alertify.error('<%= message %>');
  </script>
  <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.text_field :name, id: :sub_category_name, class: "form-control col-md-7 col-xs-12" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :category_id, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.select :category_id, options_for_select(@categories.map{ |c| [c.name, c.id] }, selected: sub_category.category_id), {include_blank: '-- select --'}, { id: 'category', class: "form-control col-md-7 col-xs-12" } %>
    </div>
  </div>

  <div class="ln_solid"></div>

  <div class="actions form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= form.submit class: "btn btn-primary" %>
      <% if sub_category.new_record? %>
      <span data-toggle="collapse" data-target="#category">New Category?</span>
      <% end %>
    </div>
  </div>
  <% end %>
</div>

app/views/sub_categories/edit.html.erb
<div class="" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>Editting Subcategory</h2>
          <div class="clearfix"></div>
        </div>
        <%= render 'form', sub_category: @sub_category %>

        <div class="pull-right">
          <%= link_to 'Show', @sub_category %> |
          <%= link_to 'Back', sub_categories_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sub_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sub Categories</h1>
<%= link_to 'New Sub Category', new_sub_category_path, class: 'btn btn-primary' %>
<% if (@sub_categories.count > 0) %>
<table id="datatable-buttons" class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Slug</th>
      <th>Show</th>
      <th>Edit</th>
   </tr>
 </thead>
  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= sub_category.name %></td>
        <td><%= Category.find(sub_category.category_id).name %></td>
        <td><%= sub_category.slug %></td>
        <td><%= link_to sub_category_path(sub_category) do %>
          <button class="btn btn-primary btn-xs" ><span class="glyphicon glyphicon-search"></span></button>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<h2>Don't have any subcategory!</h2>
<% end %>
<br>

<%= javascript_include_tag 'datatables/jquery.dataTables.min' %>
<%= javascript_include_tag 'datatables/dataTables.bootstrap' %>
<%= javascript_include_tag 'datatables/dataTables.buttons.min' %>
<%= javascript_include_tag 'datatables/jszip.min.js' %>
<%= javascript_include_tag 'datatables/pdfmake.min' %>
<%= javascript_include_tag 'datatables/vfs_fonts' %>
<%= javascript_include_tag 'datatables/buttons.html5.min' %>
<%= javascript_include_tag 'datatables/buttons.print.min' %>
<%= javascript_include_tag 'datatables/dataTables.responsive.min' %>
<%= javascript_include_tag 'datatables/responsive.bootstrap.min' %>
<%= javascript_include_tag params[:controller] %>

app/views/sub_categories/new.html.erb
<p id="notice"><%= notice %></p>

<div class="" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div id="category" class="collapse">
        <div class="x_panel">
          <div class="x_title">
            <h2>New Category</h2>
            <div class="clearfix"></div>
          </div>
          <%= render 'categories/form', category: @category %>
          <a href=""></a>
          <div class="pull-right">
            <%= link_to 'Back to category list', categories_path %>
          </div>
        </div>
      </div>

      <div class="x_panel">
        <div class="x_title">
          <h2>New Subcategory</h2>
          <div class="clearfix"></div>
        </div>
        <%= render 'form', sub_category: @sub_category %>
        <div class="pull-right">
          <%= link_to 'Back to subcategory list', sub_categories_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/sub_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sub_category.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= Category.find(@sub_category.category_id).name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @sub_category.slug %>
</p>

<%= link_to 'Edit', edit_sub_category_path(@sub_category) %> |
<%= link_to 'Back', sub_categories_path %>