config/routes.rb
Rails.application.routes.draw do
  root 'main_admin#index'
  resources :requests, only: %i[index show update destroy]
  devise_for :admins, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    password: 'secret'
  }, controllers: {
    sessions: 'admins/sessions',
    passwords: 'admins/passwords'
  }
  resources :users, only: %i[index show update]
  resources :shops, only: %i[index show update] do
    collection do
      resources :products do
        collection do
          get 'sub/:id', controller: 'products', action: 'sub'
        end
      end
    end
  end
  resources :purchase_orders, only: %i[index show new create destroy] do
    collection do
      post 'product'
      get 'products/:id', controller: 'purchase_orders', action: 'delete_product'
    end
  end
  resources :delivery_orders, only: %i[index show edit update]
  resources :categories
  resources :sub_categories
  resources :admins, only: %i[index show new create update]
  resources :main_admin, only: :index
  resources :revenue, only: :index do
    member do
      get :revenue
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  slug       :string
#

class Category < ApplicationRecord
  # =============Association==================
  has_many :sub_categories
  has_many :products, as: :categorical

  # ==============Friendly_url================
  extend FriendlyId
  friendly_id :name, use: :slugged

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  load_and_authorize_resource find_by: :slug

  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @sub_categories = SubCategory.where(category_id: @category.id)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: { message: 'Category was successfully created.' } }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: { message: 'Category was successfully updated.' } }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: { message: 'Category was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  rescue_from CanCan::AccessDenied do |exception|
    if current_admin.nil?
      flash[:error] = "Access denied: #{exception}"
      redirect_to new_admin_session_path
    else
      render file: 'public/403.html', layout: false
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  def set_category
    @category = Category.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def category_params
    params.require(:category).permit(:name, :slug)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<div class="x_content">
  <!-- start form for validation -->
  <%= form_with(model: category, local: true, id: "demo-form2", class: "form-horizontal form-label-left") do |form| %>
  <% if category.errors.any? %>
  <% category.errors.full_messages.each do |message| %>
  <script>
    alertify.set('notifier','position', 'top-right');
    alertify.error('<%= message %>');
  </script>
  <% end %>
  <% end %>

  <div class="form-group">
    <%= form.label :name, class: "control-label col-md-3 col-sm-3 col-xs-12" %>
    <div class="col-md-6 col-sm-6 col-xs-12">
      <%= form.text_field :name, id: :category_name, class: "form-control", required: true %>
    </div>
  </div>

  <div class="ln_solid"></div>

  <div class="actions form-group">
    <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
      <%= form.submit class: "btn btn-primary" %>
    </div>
  </div>
  <% end %>
  <!-- end form for validations -->

</div>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<% unless notice.nil? %>
<% unless notice['message'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.success('<%= notice['message'] %>').dismissOthers();
</script>
<% end %>
<% unless notice['errors'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= notice['errors'] %>').dismissOthers();
</script>
<% end %>
<% end %>

<div class="clearfix"></div>
<div class="col-md-12 col-sm-12 col-xs-12">
  <div class="x_panel">
    <div class="x_title">
      <h2>Categories</h2>
      <ul class="nav navbar-right panel_toolbox">
        <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
        </li>
        <li><a href="#"><i class="fa fa-close"></i></a>
        </li>
      </ul>
      <div class="clearfix"></div>
    </div>
    <div class="x_content">
      <%= link_to 'New Category', new_category_path, class: 'btn btn-primary' %>
      <% if (@categories.count > 0) %>
      <table id="datatable-buttons-category" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Slug</th>
            <th>Show</th>
            <th>Edit</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td class="slug"><%= category.slug %></td>
            <td><%= link_to category_path(category) do %>
              <button class="btn btn-primary btn-xs" ><span class="fa fa-search"></span></button>
              <% end %>
            </td>
            <td><%= link_to edit_category_path(category) do %>
              <button class="btn btn-primary btn-xs"><span class="fa fa-pencil"></span></button>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <% else %>
      <h2>Don't have any category!</h2>
      <% end %>
    </div>
  </div>
</div>

<br>
<div class="clearfix"></div>

<%= javascript_include_tag 'datatables/jquery.dataTables.min' %>
<%= javascript_include_tag 'datatables/dataTables.bootstrap' %>
<%= javascript_include_tag 'datatables/dataTables.buttons.min' %>
<%= javascript_include_tag 'datatables/jszip.min.js' %>
<%= javascript_include_tag 'datatables/pdfmake.min' %>
<%= javascript_include_tag 'datatables/vfs_fonts' %>
<%= javascript_include_tag 'datatables/buttons.html5.min' %>
<%= javascript_include_tag 'datatables/buttons.print.min' %>
<%= javascript_include_tag 'datatables/dataTables.responsive.min' %>
<%= javascript_include_tag 'datatables/responsive.bootstrap.min' %>
<%= javascript_include_tag params[:controller] %>

app/views/categories/new.html.erb
<% unless notice.nil? %>
<% unless notice['message'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.success('<%= notice['message'] %>').dismissOthers();
</script>
<% end %>
<% unless notice['errors'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= notice['errors'] %>').dismissOthers();
</script>
<% end %>
<% end %>

<div class="" role="main">
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <div class="x_panel">
        <div class="x_title">
          <h2>New Category</h2>
          <div class="clearfix"></div>
        </div>
        <%= render 'form', category: @category %>
        <div class="pull-right">
          <%= link_to 'Back', categories_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<% unless notice.nil? %>
<% unless notice['message'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.success('<%= notice['message'] %>').dismissOthers();
</script>
<% end %>
<% unless notice['errors'].nil? %>
<script type="text/javascript">
  alertify.set('notifier','position', 'top-right');
  alertify.error('<%= notice['errors'] %>').dismissOthers();
</script>
<% end %>
<% end %>
<div class="row">
  <div class="col-md-4 col-sm-4 col-xs-4">
    <p>
      <strong>Name:</strong>
      <%= @category.name %>
    </p>

    <p>
      <strong>Slug:</strong>
      <%= @category.slug %>
    </p>

    <%= link_to 'Edit', edit_category_path(@category) %> |
    <%= link_to 'Back', categories_path %>
  </div>
  <div class="col-md-8 col-sm-8 col-xs-8">
    <div class="x_panel">
      <div class="x_title">
        <h1>Sub Categories</h1>
        <%= link_to 'New Sub Category', new_sub_category_path, class: 'btn btn-primary' %>
        <br>
        <% if (@sub_categories.count > 0) %>
        <table id="datatable-buttons" class="table table-striped table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>Slug</th>
              <th>Show</th>
              <th>Edit</th>
            </tr>
          </thead>
          <tbody>
            <% @sub_categories.each do |sub_category| %>
            <tr>
              <td><%= sub_category.name %></td>
              <td><%= sub_category.slug %></td>
              <td><%= link_to sub_category_path(sub_category) do %>
                <button class="btn btn-primary btn-xs" ><span class="glyphicon glyphicon-search"></span></button>
                <% end %>
              </td>
              <td><%= link_to edit_sub_category_path(sub_category) do %>
                <button class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-pencil"></span></button>
                <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
        <% else %>
        <h2>Don't have any subcategory!</h2>
        <% end %>
        <div class="clearfix"></div>
      </div>

      <%= javascript_include_tag 'datatables/jquery.dataTables.min' %>
      <%= javascript_include_tag 'datatables/dataTables.bootstrap' %>
      <%= javascript_include_tag 'datatables/jszip.min.js' %>
      <%= javascript_include_tag 'datatables/pdfmake.min' %>
      <%= javascript_include_tag 'datatables/vfs_fonts' %>
      <%= javascript_include_tag 'datatables/buttons.print.min' %>
      <%= javascript_include_tag 'datatables/dataTables.responsive.min' %>
      <%= javascript_include_tag 'datatables/responsive.bootstrap.min' %>
      <%= javascript_include_tag params[:controller] %>